spring.application.name=youtube-telegram-downloader
public.download.dir=downloads
public.download.url=https://b0b6-149-22-84-166.ngrok-free.app/public/download
telegram.bot.file.max-size=1
public.download.file.max-size=500
server.port=8080

# Use logback-spring.xml for file configuration
# The file configuration is defined in src/main/resources/logback-spring.xml

# Conditional logging based on active profile
# You can override this with environment variable:
# export SPRING_PROFILES_ACTIVE=prod
spring.profiles.active=dev

